name: Bug Report
description: Report a bug in jodit-react
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: jodit-version
    attributes:
      label: Jodit Version
      description: What version of jodit/jodit-react are you using?
      placeholder: "e.g., 4.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React Version
      placeholder: "e.g., 18.2.0"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code to reproduce
      description: Please provide a minimal code example that reproduces the issue
      render: jsx
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or error messages here
